version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: db
    restart: unless-stopped
    ports:
      - "4444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: better
    volumes:
      - better_data:/var/lib/postgresql/data

volumes:
  better_data:
